version: "3.4"

services:
  api:
    container_name: "backend.api"
    build:
      dockerfile: $PWD/backend/docker/Dockerfile
      context: ../python
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - API_PORT=3000
      - API_HOST=0.0.0.0
      - LOGLEVEL=info
      - CLEAR_DB=
      - SCRAPER_TIMEOUT=5
      - SCRAPER_INTERVAL=86400
      - PROTOCOL_DTD_FILE=/usr/data/protocol.dtd
      - PROTOCOL_DIRECTORY=/protocols
    depends_on:
      - database
    links:
      - database
    ports:
      - 3000:3000
    networks:
      - backend

  database:
    image: mongo:latest
    container_name: "backend.database"
    volumes:
      - ~/database:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - backend
    logging:
      driver: none


networks:
  backend:
    driver: bridge
 