version: "3.4"

services:
  api:
    container_name: "backend.api"
    build:
      context: .
      target: app
    environment:
      - DB_HOST=database
      - DB_PORT=27017
      - API_PORT=3000
      - API_HOST=0.0.0.0
      - LOGLEVEL=info
    depends_on:
      - database
    links:
      - database
    ports:
      - 3000:3000
    networks:
      - backend

  database:
    image: mongo:latest
    container_name: "backend.database"
    volumes:
      - ~/database:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - backend


networks:
  backend:
    driver: bridge
 