version: "3.7"

services:
  api:
    container_name: "meinbundestag.api"
    image: "meinbundestag.api"
    build:
      dockerfile: $PWD/backend/Dockerfile
      context: $PWD/backend/python
    env_file:
      - .env
    environment:
      - LOGLEVEL=info
    depends_on:
      - database
    ports:
      - 3000:3000
    networks:
      - meinbundestag-backend

  database:
    image: mongo:latest
    container_name: "meinbundestag.database"
    volumes:
      - ./backend/meinbundestag-database:/data/db
    networks:
      - meinbundestag-backend
    env_file:
      - ./.env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    logging:
      driver: none
  
  frontend:
    container_name: "meinbundestag.frontend"
    image: "meinbundestag.frontend"
    build:
      dockerfile: $PWD/mobile/Dockerfile
      context: $PWD/mobile/meinbundestag-mobile
    env_file:
      - .env
    environment:
      - LOGLEVEL=info
    volumes:
      - $PWD/mobile/meinbundestag-mobile/src:/usr/src/app/src
    depends_on:
      - api
    ports:
      - 127.0.0.1:19000-19006:19000-19006
      

networks:
  meinbundestag-backend:
    driver: bridge
    external: true
