version: "3.7"

services:
  api:
    container_name: "meinbundestag.api"
    image: "meinbundestag.api"
    build:
      dockerfile: $PWD/backend/docker/Dockerfile
      context: $PWD/backend/python
    env_file:
      - .env
    environment:
      - LOGLEVEL=info
    depends_on:
      - database
    links:
      - database
    ports:
      - 3000:3000
    networks:
      - meinbundestag-backend-api
      - meinbundestag-backend

  database:
    image: mongo:latest
    container_name: "meinbundestag.database"
    volumes:
      - ./backend/meinbundestag-database:/data/db
    ports:
      - 27017-27019:27017-27019
    networks:
      - meinbundestag-backend
    env_file:
      - .env
    environment: 
      - MONGO_INITDB_ROOT_USERNAME=${DB_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${DB_PASSWORD}
    logging:
      driver: none
  
  mobile:
    container_name: "meinbundestag.mobile"
    image: "meinbundestag.mobile"
    build:
      dockerfile: $PWD/mobile/docker/Dockerfile
      context: $PWD/mobile/meinbundestag-mobile
    #volumes:
    #  - '$PWD/mobile/meinbundestag-mobile:/usr/src/app'
      #- /dev/null:/usr/src/app/.expo
      #- /usr/src/app/.expo-shared
      #- /usr/src/app/.node_modules
      #- /usr/src/app/.yarnclean
    ports:
      - 19000:19000
      - 19002:19002
      - 19001:19001
      - 19006:19006
    networks:
      - meinbundestag-backend-api

networks:
  meinbundestag-backend:
    driver: bridge
    external: true
  meinbundestag-backend-api:
    driver: bridge
    external: true